
tools:
    exceptions: https://sentry.io/organizations/sphinx-model/issues/?project=5479436
    model-ci: https://github.com/dcsil/sphinx-model/blob/main/.github/workflows/model_env.yml
  
  services:
    production: https://dashboard.heroku.com/apps/sphinx-model
  
  docs:
    getting_started: ./README.md
    
  commands:
    bootstrap: script/bootstrap
    server: python3 app.py
    test: python3 -m pytest -v