tools:
    exceptions: https://sentry.io/organizations/dcsil/issues/?project=5450612
    logging: ''
    ci: https://github.com/dcsil/sphinx-model/blob/main/.github/workflows/model_env.yml
  
services:
    production: https://dashboard.heroku.com/apps/sphinx-model

docs:
    getting_started: ./README.md

commands:
    bootstrap: chmod 700 script/bootstrap; script/bootstrap
    database: ''
    server: python3 app.py
    test: python3 -m pytest -v
