# Github actions for Flask model environment

name: Coverage

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  coverage:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: upload code climate
        env:
          CC_TEST_REPORTER_ID: 66879998ad8298583bae9ae44cfd18829a4c449859d762ff8a3133130ce87def
        run: |
          export GIT_BRANCH="${GITHUB_REF##*/}"
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter format-coverage -t coverage.py
          ./cc-test-reporter upload-coverage --id $CC_TEST_REPORTER_ID